modLoader="javafml"
loaderVersion="[48,)"
license = "CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/MattCzyr/RealisticTorches/issues"
[[mods]]
    modId="realistictorches"
    version="1.20.2-3.2.0"
    displayName="Realistic Torches"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-torches"
    authors="ChaosTheDude"
    description='''
    Makes torches burn out after a configurable amount of time.
    '''

[[dependencies.realistictorches]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.realistictorches]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,)"
    ordering="AFTER"
    side="BOTH"